version: "3.7"

####################### Services Definition #######################
services:

  server-prod:
    container_name: server_prod
    image: server:prod
    build:
      context: .
      dockerfile: Dockerfile.production
    ports:
      - 5000:5000
    environment:
      - PORT=5000
      - DATABASE_URL=postgres://admin:password@database_prod:5435/prod_db
    depends_on:
      - database-prod
    networks:
      - default

  database-prod:
    container_name: database_prod
    image: postgres:12-alpine
    volumes:
      - "db-data:/var/lib/postgresql/data"
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=prod_db
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=password
    networks:
      - default

####################### Networks Definition #######################
networks:
  default:
    driver: bridge

####################### Volumes Definition ########################
volumes:
  db-data:
    driver: local
