version: "3.7"

####################### Services Definition #######################
services:

  server-dev:
    container_name: server_dev
    image: server:dev
    build:
      context: .
      dockerfile: Dockerfile.development
    volumes:
      - "./:/usr/src/app"
      - "/usr/src/app/node_modules"
    ports:
      - 5000:5000
    environment:
      - PORT=5000
      - DATABASE_URL=postgres://admin:password@database_dev:5432/dev_db
    depends_on:
      - database-dev
    networks:
      - default

  database-dev:
    container_name: database_dev
    image: postgres:12-alpine
    volumes:
      - "db-data:/var/lib/postgresql/data"
    ports:
      - 5435:5432
    environment:
      - POSTGRES_DB=dev_db
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=password
    networks:
      - default

####################### Networks Definition #######################
networks:
  default:
    driver: bridge

####################### Volumes Definition ########################
volumes:
  db-data:
    driver: local
