name: Continuous Integration

on: [pull_request]

jobs:
  test:
    name: Run server and client tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Run server tests
        run: (cd .scripts && bash local.sh test_server)

      - name: Run client tests
        run: (cd .scripts && bash local.sh test_client)
